import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiTwotoneMail,
} from "react-icons/ai";
import Image from 'next/image';
import picture1 from '../public/picture1.jpg'
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from "react";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Salmaan Mahamoud Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>Developed by Salmaan Mahamoud</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li>
              <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Salmaan Mahamoud</h2>
            <h3 className="text-2xl py-2">FrontEnd Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>from Leicester</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
          <AiFillGithub/>
            <AiFillLinkedin/>
            <AiTwotoneMail/>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={picture1} layout="fill" objectFit="cover" />
          </div>
        </section>
       
        <section>
          <div>
            <h3 className='text-3xl py-1'>My Projects</h3>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div>
              <Image src={web1} />
              </div>
              <div>
              <Image src={web2} />
              </div>
              <div>
              <Image src={web3} />
              </div>
              <div>
              <Image src={web4} />
              </div>
              <div>
              <Image src={web5} />
              </div>
              <div>
              <Image src={web6} />
              </div>

          </div>
        </section>
      </main>
    </div>
  )
}
