import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiTwotoneMail,
} from "react-icons/ai";
import Image from 'next/image';
import picture1 from '../public/picture1.jpg'
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
//import web6 from "../public/web6.png"
//import web7 from "../public/web7.png"
import { useState } from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Salmaan Mahamoud Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">developed by salmaan</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/13OMqWJzBsO21vRkC-y5KExzwCEftyys9/view?usp=sharing"
                >
                  View CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-extrabold">Salmaan Mahamoud</h2>
            <h3 className="text-2xl py-2 font-bold dark:text-white">Software Developer</h3>
            <p className="text-md py-5 font-medium leading-8 text-gray-800 dark:text-gray-200">
              from Leicester
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href="https://github.com/smahamoud" role="button">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/salmaan-mahamoud-981a9025a/" role="button">
              <AiFillLinkedin />
            </a>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={picture1} layout="fill" objectFit="cover" alt="Salmaan's Picture" />
          </div>
        </section>

        <section>
          <div className="flex justify-center">
            <h3 className="text-3xl py-1 mt-20 font-bold dark:text-gray-200">My Projects</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/4 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <a href="https://github.com/smahamoud/take-home-salary-calculator-react">
                <Image src={web1} className="rounded-lg object-cover" layout="responsive" width={100} height={100} alt="Take home salary project" />
              </a>
              <h2 className="flex justify-center text-m font-bold dark:text-gray-200">
                Take home salary <AiFillGithub />
              </h2>
            </div>

            <div className="basis-1/4 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <a href="https://github.com/smahamoud/SpotifySearcher">
                <Image src={web2} className="rounded-lg object-cover" layout="responsive" width={100} height={100} alt="Spotify Searcher project" />
              </a>
              <h2 className="flex justify-center text-m font-bold dark:text-gray-200">
                Spotify Searcher <AiFillGithub />
              </h2>
            </div>

            <div className="basis-1/4 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <a href="https://github.com/smahamoud/pokedex-react">
                <Image src={web3} className="rounded-lg object-cover" layout="responsive" width={100} height={100} alt="Pokedex project" />
              </a>
              <h2 className="flex justify-center text-m font-bold dark:text-gray-200">
                Pokedex <AiFillGithub />
              </h2>
            </div>

            <div className="basis-1/4 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <a href="https://github.com/smahamoud/recipe-app">
                <Image src={web4} className="rounded-lg object-cover" layout="responsive" width={100} height={100} alt="Recipe app project" />
              </a>
              <h2 className="flex justify-center text-m font-bold dark:text-gray-200">
                Recipe app <AiFillGithub />
              </h2>
            </div>

            <div className="basis-1/4 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <a href="https://github.com/smahamoud/todo-list">
                <Image src={web5} className="rounded-lg object-cover" layout="responsive" width={100} height={100} alt="To do list project" />
              </a>
              <h2 className="flex justify-center text-m font-bold dark:text-gray-200">
                To do list <AiFillGithub />
              </h2>
            </div>

            <div className="basis-1/4 flex-1 transition ease-in-out delay-150 hover:-translate-y-1 hover:scale-110 duration-300">
              <a href="https://github.com/smahamoud">
                <Image src={web1} className="rounded-lg object-cover" layout="responsive" width={100} height={100} alt="Coming soon project" />
              </a>
              <h2 className="flex justify-center text-m font-bold dark:text-gray-200">
                Coming soon <AiFillGithub />
              </h2>
            </div>
          </div>
          <div className="flex justify-center">
            <a
              href="https://github.com/smahamoud"
              className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
            >
              View more
            </a>
          </div>
        </section>

        <section>
          <div className="flex justify-center">
            <h2 className="text-3xl py-1 mt-20 font-bold dark:text-gray-200">About me</h2>
          </div>
          <div className="text-center">
            <h3 className="text-3xl py-2 font-semibold dark:text-white">Hey, I&apos;m Salmaan</h3>
            <p className="text-md py-5 font-medium leading-8 text-gray-800 dark:text-gray-200">
            I began learning how to code during the fall of 2022 by building projects through the freeCodeCamp website. Since then, I have used Codecademy courses to learn languages such as Python, TypeScript, React Native, SQL and more. I have further honed my skills through the Coding Bootcamp Course at Purple Beard, which provided me with comprehensive training in software development. Additionally, I bring two years of customer service experience, where I developed strong communication, problem-solving, and interpersonal skills that are invaluable in any professional setting.

While I am eager to begin a career in tech, I also have many hobbies and interests. One of them is a deep appreciation for both non-fiction and fiction literature, recognizing the vital roles they play in personal growth and development. And I enjoy weekly hikes to Wales and all over England. I also take part in volunteering for charities such as Living with Abuse and Cancer research, I plan on taking part in another event for Cancer Research UK in October 202
 
            </p>
          </div>
          <div className="flex justify-center">
            <a
              href="https://www.linkedin.com/in/salmaan-mahamoud-981a9025a/"
              className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"> View more
            </a>
          </div>
        </section>
        <div className="mb-20"></div>
      </main>
    </div>
  );
}